name: Proxmox Disk Temperature Monitor CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install smartmontools
        run: sudo apt-get update && sudo apt-get install -y smartmontools

      - name: Make script executable
        run: chmod +x proxmox-disk-temp.sh

      - name: Run Disk Temperature Monitor
        run: ./proxmox-disk-temp.sh
